import { useState } from "react";
import { ArrowRight, Check, ChevronRight, Code2, Mic, Moon, Pause, Play, RotateCcw, Volume2, X } from "lucide-react";

const nav = ["Today", "Practice", "Progress", "History"];
const E = ({ children }) => <p className="eyebrow">{children}</p>;
function Mark({ go }) { return <button className="wordmark" onClick={() => go("landing")}>Interviewer</button>; }
function Header({ page, go, dark, onTheme }) { return <header className="header"><Mark go={go}/>{page === "landing" ? <nav><a href="#how">How it works</a><a href="#rounds">Rounds</a><a href="#pricing">Pricing</a></nav> : <nav>{nav.map(x => <button className={page === x.toLowerCase() ? "active" : ""} onClick={() => go(x.toLowerCase())} key={x}>{x}</button>)}</nav>}<div><button className="theme-toggle" onClick={onTheme} aria-label={dark ? "Use light mode" : "Use dark mode"}><Moon/></button>{page === "landing" ? <><button className="plain">Sign in</button><Button onClick={() => go("today")}>Start <ArrowRight/></Button></> : <b className="avatar">PS</b>}</div></header>; }
function Button({ children, onClick, light=false }) { return <button onClick={onClick} className={light ? "button light" : "button"}>{children}</button>; }
function Close({ go, title, live=false }) { return <header className="session-head"><Mark go={go}/><div><b>{title}</b>{live && <><span>Stage 2 of 4: Implementation</span><time>24:18</time><button className="plain"><Pause/> Pause</button></>}</div><button className="plain" onClick={() => go("today")}><X/></button></header>; }

function Landing({ go, dark, onTheme }) { return <><Header page="landing" go={go} dark={dark} onTheme={onTheme}/><main><section className="hero"><div><E>Practice with proof</E><h1>The interview you get to fail first.</h1><p className="lede">A voice interviewer that asks one question, follows up on your answer, and scores you with evidence you can read back.</p><div className="actions"><Button onClick={() => go("setup")}>Start a free round <ArrowRight/></Button><button className="under" onClick={() => go("report")}>See a report <ArrowRight/></button></div><small>45 min · voice or text · no credit card</small></div><article className="preview"><header><time>00:14:22</time><time>DSA · round 1 of 1</time></header><p><b>AI</b>“Your loop is O(n²). What would you change?”</p><p className="you"><b>You</b>“Use a hash set for...”</p><footer><Check/> tests 3/4 pass</footer></article></section><section className="steps" id="how">{[["01","Book a round","role, level, focus"],["02","Get interviewed","one question at a time, real follow-ups"],["03","Read the evidence","every score quotes what you said, tests shown separately"]].map(x => <article key={x[0]}><E>{x[0]}</E><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</section><section className="specimen"><E>Specimen report <span>anonymised, expandable</span></E><button onClick={() => go("report")}>Verdict: borderline at L4 <i/> Problem solving 3/4 <i/> Communication 2/4 <ArrowRight/></button></section><p className="guard">What it will not do: predict a yes at a named company · replace practice with real humans · grade you on typing speed</p></main></>; }

function Today({ go, dark, onTheme }) { return <><Header page="today" go={go} dark={dark} onTheme={onTheme}/><main className="today"><section><E>Next up</E><article className="next"><div><h2>Concurrency under load <span>· 25 min · drill</span></h2><p>Why: you lost the last two rounds on shared-state reasoning <em>(Sep 2, Aug 28)</em></p><small>hints on · no overall score</small></div><div><Button onClick={() => go("setup")}>Start <ArrowRight/></Button><button className="under">Choose something else</button></div></article><section className="recent"><E>Recent</E>{[["Sep 2","Full mock · DSA","2.6/4"],["Aug 28","Topic · concurrency","2.1/4"],["Aug 24","Full mock · DSA","2.4/4"]].map(x=><button onClick={()=>go("report")} key={x[0]}><time>{x[0]}</time><b>{x[1]}</b><span>{x[2]} <ArrowRight/></span></button>)}</section></section><aside className="readiness"><E>Readiness <span>Backend L4</span></E><div className="meter"><div><i/><i/><i/><i/><i/></div><b>62</b></div><p>from 6 rounds, 3 competencies<br/>untested: system design</p><hr/><div><E>This week</E><b>2 of 3 sessions</b><br/><small>goal set by you, editable</small></div><hr/><div><E>Last report <span>Sep 2</span></E><b>Borderline at L4</b><br/><small>Problem solving &nbsp; 3/4 ↑<br/>Communication &nbsp; 2/4 flat</small></div><button className="under" onClick={() => go("report")}>Open report <ArrowRight/></button></aside></main></>; }

function Setup({ go }) { return <div className="session"><Close go={go} title="Set up your round"/><main className="setup"><E>Your next round</E><h1>Practice one thing<br/><em>properly.</em></h1><div className="fields"><label>Round type<select><option>Full mock</option><option>Topic focus</option></select></label><label>Target level<select><option>Backend L4</option><option>Backend L3</option></select></label><label>Focus<input defaultValue="Concurrency under load"/></label></div><p className="meta">25 min <i/> Voice or text <i/> Hints on</p><Button onClick={() => go("lobby")}>Continue <ArrowRight/></Button></main></div>; }
function Lobby({ go }) { return <div className="session"><Close go={go} title="Round lobby"/><main className="lobby"><section><E>Lobby</E><h1>Backend L4<br/>full mock</h1><p className="meta">45 min · realistic mode</p><div className="mic"><Mic/><span><b>Microphone</b><small>Default · MacBook</small></span><i/><i/><i/><i/></div><E>House rules</E><ol><li>one question at a time</li><li>ask for clarification freely</li><li>hints are logged, not banned</li><li>pause any time - clock stops</li></ol><p className="note">The interviewer knows: your level, last 3 reports, stack.</p><Button onClick={() => go("live")}>Begin <Play/></Button></section><Trace/></main></div>; }
function Trace(){const rows=[["00:00","plan","round: 4 stages"],["00:03","memory","read 3 weak areas"],["00:04","ask","stage 1 question"],["00:09","decide","follow-up: concurrency"],["00:22","tool","run_tests 1.4s ok"],["00:40","score","rubric pass, 4 comps"]];return <aside className="trace"><E>Agent trace <span>developer mode</span></E><p>Session 8f21 · 43 min · 26 steps</p>{rows.map(x=><div key={x[0]}><time>{x[0]}</time><b>{x[1]}</b><span>{x[2]}</span></div>)}</aside>}
function Live({ go }) { const [tested,setTested]=useState(false); return <div className="session live"><Close go={go} title="Full mock · Backend L4" live/><div className="stages"><i/><i/><i className="now"/><i/><span>intro / approach / implement / wrap</span></div><main className="work"><section className="question"><E>Question</E><h2>Rate limiter for an API gateway.</h2><p>10k req/s, per-key limits, multiple nodes.</p><Button light>Show constraints</Button><div className="transcript"><E>Transcript</E><p><time>00:04</time><b>AI</b> Walk me through the approach before you write anything.</p><p><time>00:06</time><b>You</b> I would use a token bucket per key...</p><p><time>00:09</time><b>AI</b> What happens when the same key hits two nodes?<small>└ follow-up</small></p></div><p className="listening"><Volume2/> interviewer is listening <i/><i/><i/></p></section><section className="code"><header><span><Code2/> solution.py</span><select><option>Python</option></select><Button onClick={()=>setTested(true)}>{tested ? "Tests complete" : "Run tests"} <Play/></Button></header><pre>{`1  class RateLimiter:\n2    def __init__(self, rps):\n3      self.rps = rps\n4      self.buckets = {}\n5\n6    def allow(self, key):\n7      # token bucket\n8      ...`}</pre><div className="tests"><E>Tests <span>objective - not the interviewer</span></E>{[["PASS","single key under limit","12ms"],["PASS","burst then refill","31ms"],["FAIL","concurrent keys","expected 200, got 173"]].map(x=><p className={x[0].toLowerCase()} key={x[1]}><b>{x[0]}</b><span>{x[1]}</span><small>{x[2]}</small></p>)}<small>{tested ? "complete" : "···· running: clock skew"}</small></div></section></main><footer className="controls"><button><Mic/> Hold to speak</button><button>Type instead</button><button>Ask for clarification</button><button>Hint <span>(1 of 3)</span></button></footer><button className="finish" onClick={()=>go("report")}>Finish demo <ChevronRight/></button></div>}
function Score({name,note,up}) { return <p className="score"><span>{name}</span><i><b style={{width:note[0]*25+"%"}}/></i><strong>{note}</strong><small>{up}</small></p> }
function Report({ go }) { return <div className="session"><Close go={go} title="Full mock · Backend L4 · Sep 2 · 43 min"/><main className="report"><header className="verdict"><div><E>Borderline at L4</E><b>2.6 <small>/ 4</small></b><span>you predicted 3.0</span></div><p>“Correct approach, arrived at slowly; the concurrency case was never handled.”</p><Button light><RotateCcw/> Start revision</Button></header><section className="scores"><div><E>AI judgement</E><Score name="Problem solving" note="3/4" up="↑ +0.5"/><Score name="Coding" note="2/4" up="= flat"/><Score name="Communication" note="2/4" up="↓ -0.5"/><Score name="Depth of follow-up" note="3/4" up="new"/><small>confidence: high on coding,<br/>low on communication (7 min of audio)</small></div><div><E>Objective results</E>{[["Tests","3 of 4 passed"],["Complexity","O(1) per call · stated"],["Time to work","8 min 40 s"],["Hints used","1 of 3"]].map(x=><p className="objective" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}<small>measured, not judged</small></div></section><section className="evidence"><header><div>↓ Communication <b>2/4</b></div><Button light>Challenge this score</Button></header><p>Because: you answered before restating the requirement, twice.</p><blockquote><b>Evidence</b> <time>00:06</time> “I would use a token bucket per key” <a>jump to moment →</a></blockquote><blockquote><b>Evidence</b> <time>00:31</time> (34 s of silence while editing, no narration)</blockquote><div className="stronger"><b>Stronger</b><p>“Let me restate: per-key limits, 10k/s, multi-node. I will start single-node, then make the counter shared.”<small>why: it makes your assumptions checkable before you spend eight minutes.</small></p></div></section><footer>vs Aug 24 (same round type): overall 2.4 → 2.6 <span>coding flat</span> <span>comms -0.5</span></footer></main></div> }
function Empty({page,go,dark,onTheme}) { return <><Header page={page} go={go} dark={dark} onTheme={onTheme}/><main className="empty"><E>{page}</E><h1>{page === "practice" ? "Choose what to rehearse." : `${page}, with evidence.`}</h1><p>This screen will connect to saved sessions once the backend is ready.</p><Button onClick={()=>go("today")}>Back to today <ArrowRight/></Button></main></> }
export default function App(){const [page,go]=useState("landing");const [dark,setDark]=useState(false);const props={go,dark,onTheme:()=>setDark(value=>!value)};let screen;if(page==="landing")screen=<Landing {...props}/>;else if(page==="today")screen=<Today {...props}/>;else if(page==="setup")screen=<Setup go={go}/>;else if(page==="lobby")screen=<Lobby go={go}/>;else if(page==="live")screen=<Live go={go}/>;else if(page==="report")screen=<Report go={go}/>;else screen=<Empty page={page} {...props}/>;return <div className={dark ? "dark-mode" : ""}>{screen}</div>}
